### ISSUE TITLE
How to begin

### ISSUE THREAD

**Issue by Bryankaveen** [Bryankaveen/Eyes-The-Horror-Game-CE#1]
This game is going to be a perfect clone of Eyes - The Horror Game
For those who don't know what game is it, please download the original version (available on Play Store and Apple Store) ;)

The main problem is: should I adapt the game into a 2D version ?
Indeed, the fact of including 4 monsters in-game, and big maps, might result in a heavy file-in.8xp. Plus, the gameplay will be slow.

So, who is for a 2D version of the game?

**Comment by KingDubDub** [comment]
Hi, I received an invitation to join as a collaborator for this, and I think the logic was "this man copy phone game, he know how do thing" to which I respond "No. No know what do, just do thing until thing run."

Since this looks like a cool project (and I'm having my monthly project burnout) here's some tips on what to do:
1. Make a post on cemetech.net, I am not anywhere close to the level that people on there are at skill-wise, I just have a shallow knowledge about how to approach things that helps me learn. The forums are your friend.
2. Learn how to use [Tiled for mapmaking](https://github.com/mapeditor/tiled), it's in the CE C Toolchain docs.
3.  Pin [said docs](https://ce-programming.github.io/toolchain/index.html) to your browser taskbar, it will save your life.
4. Yes, make it 2D. There're two 3D games for the CE that I know of that kinda work, one of which is an unfinished DOOM clone. 3D rendering works but it's not something I've studied as it never looked like something I could run quickly with C. Feel free to try it if you think it'll work.
5. Maps are limited to 256*256, and that will max out an appvar easily. Compression would help keep things small, and low-res sprites are to be expected anyway.

Ask anything else if you want, the only horror games I've ever played was that Granny one and Zardy's Maze, so I'm not an expert. I would like to help though, I have not seen a horror game for the CE or any calculator yet and would like to help move the genre forward.

**Comment by Bryankaveen** [comment]
Thanks for your ideas !
Actually, I'm not a man, I'm only 16 XD

So, ok, I'll build 2D maps (redpoint for the monster, and black for the player)
PS: a gameplay of the original game https://www.youtube.com/watch?v=foB4knUYkIQ

**Comment by KingDubDub** [comment]
Ah okay, I found your account after searching your handle. I wasn't calling you a man, I was narrating what I thought your logic was for asking me, and no, I'm not a C++ super-epic-master like most people (I'm only 18 myself, but I admit that I don't act like it). I'm trying to master C though, since it could help me land a job in the future or at least give me a fun hobby. You don't have to use Tiled, it just works well. The normal way to make maps is with convbin in the toolchain, which you can use to take a .csv file and generate an appvar with the data in it. Anything that can generate a .csv will work with it, even Microsoft Excel or notepad. Tiled is just really convenient and easy to use.

**Comment by Bryankaveen** [comment]
Do you know how to build a logo with convimg ? 
I forgot how to use it ...

**Comment by adriweb** [comment]
The toolchain has many examples for convimg :)

**Comment by Bryankaveen** [comment]
Thanks, but where can I find it?

**Comment by KingDubDub** [comment]
Examples: /CEdev/examples/graphx

[The graphx documentation has insturctions on how to use convimg as well.](https://ce-programming.github.io/toolchain/libraries/graphx.html)
